version: "3.0"

services:
    xmrig:
      build:
        dockerfile: docker/xmrig.dockerfile
        context: ./
      container_name: "mine"
      runtime: nvidia
      volumes: 
        - ./config.json:/usr/local/bin/config.json
    phoenix:
      build:
        dockerfile: docker/phoenix.dockerfile
        context: ./
      container_name: "phoenix"
      runtime: nvidia
      volumes: 
        - ./phoenix/config.txt:/usr/local/bin/PhoenixMiner_5.5c_Linux/config.txt
    kpa:
      build:
        dockerfile: docker/nb.dockerfile
        context: ./
      container_name: "kpa"
      runtime: nvidia
    
    bminer:
      build:
        dockerfile: docker/bminer.dockerfile
        context: ./
      container_name: "bminer"
      runtime: nvidia
    
    lolminer:
      build:
        dockerfile: docker/lolminer.dockerfile
        context: ./
      container_name: "lol"
      runtime: nvidia
    
    gminer:
      build:
        dockerfile: docker/gminer.dockerfile
        context: ./
      container_name: "gminer"
      runtime: nvidia